### PR TITLE
216 - NatsConnection thread pool

### PR DESCRIPTION
**Pull request by kedzie**

### CODE REVIEW

**Comment by sasbury** [comment]
Thinking on this. I actually had it on my todo for a while, but realized that threads aren't recycled so the pool is just providing a place to make new threads, but we aren't using anything "pool like". What was your motivation? Maybe i just gave up too soon.

**Comment by kedzie** [comment]
The idea would be to have it configurable.  So one could pass in an Executor implementation in the Options.   By default a CachedThreadPool would only offer benefit if threads were reused.  There are threads made for Draining i believe.  Or if dispatchers are created and removed.

**Comment by sasbury** [comment]
I will take a look this week, trying to wrap something up.

**Comment by sasbury** [comment]
Planning to pull this in today, i am going to do a few changes to support naming (which helps in debugging) and also to put the default into the options object.

**Pull request merged**
