### PR TITLE
#184 Android compatibility pre API 24

### PR DESCRIPTION
**Pull request by kedzie**

### CODE REVIEW

**Comment by kedzie** [comment]
This is for issue #184

**Comment by kedzie** [comment]
I replaced `CompletableFuture` everywhere with an implementation based on `CountDownLatch`.  I even replaced it in the tests/examples, which we could undo to make the PR smaller.

**Comment by sasbury** [comment]
This looks like a really clean way to port to Android. There is another PR that uses a different dependency, but I like how you just implemented what you need with available JDK classes.

I am still thinking we need a new repo because this is a Major API change, it will break existing users by changing imported classes. The other reason I have been thinking of Android as a separate repo is that there are likely power/network optimizations that apply to mobile and not desktop/server.

**Comment by kedzie** [comment]
Do you want to maintain it?  Start a new repo in the nats-io org will give the android project exposure, vs leaving it in my fork

**Comment by sasbury** [comment]
I have a biz trip next week, but will think on how we want to handle this, we may bring it in but try to get some outside maintainer support (would you be up for something like that?) I haven't talked to the team but that would probably work better than a non-android developer maintaining.

**Comment by kedzie** [comment]
I'd be happy to contribute my efforts.

**Comment by sasbury** [comment]
I talked to the team, the preferred path is to have you make a fork, and then we will add it to the community library list on the site, that way people can find it. Moving forward we can decide if it should get adopted in. Does that seem reasonable? Would you be willing to have us point to your version?

**Comment by kedzie** [comment]
Yes I'd be glad to have you guys point to it.

**Comment by kedzie** [comment]
I will also merge my changes to master on my fork and rebrand the resume to nats android.

**Comment by sasbury** [comment]
Sounds good, ping the final repo URL and I will get it on the site, and maybe add something to the readme here.

**Comment by kedzie** [comment]
Hey I have a unrelated question.   on `NatsDispatcher` in the `subscribeImpl` method line 186 does ```sub = connection.createSubscription(subject, queueName, this);
            NatsSubscription actual = subscriptions.putIfAbsent(subject, sub);
            if (actual != null) {
                this.connection.unsubscribe(sub, -1); // Could happen on very bad timing
            }``` . This comment confused me because `putIfAbsent` always returns a value.  either the existing value or the newly inserted value.  So `actual != null` is **always true**.  So it will unsubscribe... and this

**Comment by sasbury** [comment]
For concurrent hash map the doc says "Returns: the previous value associated with the specified key, or null if there was no mapping for the key" so it should be null unless the subscription was already there. I am looking at jdk 8, maybe it changed somewhere?

**Comment by kedzie** [comment]
I updated the readme and included an Android example app.  Will have to figure out travis builds and publish the artifact somewhere.   [nats-android](https://github.com/SpotOnInc/nats-android)

**Comment by kedzie** [comment]
In the Android JDK 8 it is implemented as
```
default V putIfAbsent(K key, V value) {
        V v = get(key);
        if (v == null) {
            v = put(key, value);
        }

        return v;
    }
```

**Comment by kedzie** [comment]
Yes you were correct about the `putIfAbsent` only returns when as value was already there.  My mistake I will implement the same behavior.

**Comment by sasbury** [comment]
Closing the PR, now that we have https://github.com/SpotOnInc/nats-android on nats.io :-)

**Pull request closed without merging**
