### PR TITLE
Added methods for Scatter-Gather pattern

### PR DESCRIPTION
**Pull request by Hronom**
Added methods for Scatter-Gather pattern basic realization #93

### CODE REVIEW

**Comment by ColinSullivan1** [comment]
@Hronom , Thank you for the contribution!  We apologize for not getting back to you sooner.

We generally have the Apcera supported client APIs follow our canonical client, the go client, unless there is something idiomatic with the language we feel we should support.  Following the tenet of NATS simplicity, we're very hesitant to add new APIs.

This functionality seems to cover a use case that has come up more than a few times.  That being said, this may be better served as an example pattern we can showcase elsewhere.  We've had discussions about providing a repository of examples using different messaging patterns; this could be a good candidate for that.

I'll let you know.

Thanks,
Colin

**Comment by ColinSullivan1** [comment]
@Hronom , we'll demonstrate this pattern in some example code.

**Comment by sasbury** [comment]
This PR has gotten out of date, if you have some ideas for the 2.x branch please update and submit those. I dislike closing peoples work, but things changed too much to use this version.

**Comment by Hronom** [comment]
After 3 years... well we don't use NATS for now, so info for community: I don't have time to renew code and make pull request again, sorry.

**Pull request closed without merging**
