### PR TITLE
Backport to Java 7 and Android API less 26 

### PR DESCRIPTION
**Pull request by AcoustickSan**
On Android use [ThreeTenABP](https://github.com/JakeWharton/ThreeTenABP), on Java [ThreeTen](https://www.threeten.org/threetenbp/)

### CODE REVIEW

**Comment by sasbury** [comment]
I think we should do this as a fork. I am worried that backporting to Java 7, when Java 8 is already old is the wrong direction for the library, but I also understand the need to deal with android fragmentation.

**Comment by AcoustickSan** [comment]
Ok. Can I create new repo with android example and publish library with link for you as original?

**Comment by sasbury** [comment]
If you fork the repo to create a Java 7/Android version, GitHub will link back to the original (and point the other way), but I can also add a link to the readme here so that others can find your work. I keep hoping Google will push Java 8 to every Android phone but I know that just isn't in the cards yet.

**Comment by sasbury** [comment]
Closing in favor of https://github.com/SpotOnInc/nats-android. Sorry for the delays in resolving.

**Pull request closed without merging**
